apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Reference the deployment manifest
resources:
  - deployment.yaml
# Dynamically set the Docker image name and tag
images:
  - name: IMAGE_PLACEHOLDER # Matches placeholder in deployment.yaml
    newName: "396608779072.dkr.ecr.us-east-1.amazonaws.com/lab2-chrisley75-ecr-l5e" # Can be changed dynamically
    newTag: "build-20251121-203746-2f36f54-43" # Can be updated via CI/CD
